# Generated by Django 4.1.5 on 2023-01-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_medicationorder_b12_10ml_medicationorder_bpc_157_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationorder',
            name='cabergoline',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='expedited_shipping',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='metformin',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='modafanil',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='phentermine',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='semaglutide_l1',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='semaglutide_l2',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255),
        ),
    ]
