# Generated by Django 4.1.5 on 2023-01-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_alter_medicationorder_cabergoline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationorder',
            name='syringes',
            field=models.CharField(choices=[('0', '0'), ('30g x 1/2" x 1ml', '30g x 1/2" x 1ml'), ('25g x 1" x 3ml', '25g x 1" x 3ml'), ('30g x 5/16" x 1ml', '30g x 5/16" x 1ml')], default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='bpc_157',
            field=models.CharField(choices=[('0', '0'), ('1 Month', '1 Month $226'), ('2 Month', '2 Month $400'), ('3 Month', '3 Month $600')], default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='bpc_157_c',
            field=models.CharField(choices=[('0', '0'), ('1 Month', '1 Month $180'), ('2 Month', '2 Month $348'), ('3 Month', '3 Month $511')], default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='dhea',
            field=models.CharField(choices=[('0', '0'), ('10 Tablets', '10 Tablets: $40'), ('15 Tablets', '15 Tablets: $60'), ('20 Tablets', '20 Tablets: $75'), ('30 Tablets', '30 Tablets: $113')], default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='ed_max',
            field=models.CharField(choices=[('0', '0'), ('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30')], default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='finasteride',
            field=models.CharField(choices=[('0', '0'), ('30 Tablets', '30 Tablets: $40'), ('60 Tablets', '60 Tablets: $74')], default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='ipa',
            field=models.CharField(choices=[('0', '0'), ('1 Month', '1 Month $255'), ('2 Month', '2 Month $430'), ('3 Month', '3 Month $635')], default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='ipa_cjc',
            field=models.CharField(choices=[('0', '0'), ('1 Month', '1 Month $255'), ('2 Month', '2 Month $430'), ('3 Month', '3 Month $635')], default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='mic_oral',
            field=models.CharField(choices=[('0', '0'), ('One Month', 'One Month: 30 tablets $86.50'), ('Two Months', 'Two Months: 60 tablets $163.50'), ('Three Months', 'Three Months: 90 tablets $241.50')], default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='mk_677',
            field=models.CharField(choices=[('0', '0'), ('1 Month', '1 Month $195'), ('2 Month', '2 Month $380'), ('3 Month', '3 Month $570')], default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='pregnelone',
            field=models.CharField(choices=[('0', '0'), ('30 Tablets', '30 Tablets: $79'), ('60 Tablets', '60 Tablets: $149')], default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='sermorelin',
            field=models.CharField(choices=[('0', '0'), ('1 Month', '1 Month $211.65'), ('2 Month', '2 Month $400'), ('3 Month', '3 Month $598')], default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='sermorelin_p',
            field=models.CharField(choices=[('0', '0'), ('1 Month', '1 Month $183'), ('2 Month', '2 Month $355'), ('3 Month', '3 Month $530')], default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='sildenafil',
            field=models.CharField(choices=[('0', '0'), ('10 Tablets', '10 Tablets: $62.50'), ('15 Tablets', '15 Tablets: $90'), ('20 Tablets', '20 Tablets: $120'), ('30 Tablets', '30 Tablets: $180')], default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='tadalafil',
            field=models.CharField(choices=[('0', '0'), ('10 Tablets', '10 Tablets: $72.50'), ('15 Tablets', '15 Tablets: $100'), ('20 Tablets', '20 Tablets: $140'), ('30 Tablets', '30 Tablets: $210')], default='0', max_length=25),
        ),
    ]
