# Generated by Django 4.1.5 on 2023-01-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_medicationorder_syringes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationorder',
            name='testosterone',
            field=models.CharField(choices=[('IM', 'IM (intramuscular) - injecting into the muscle'), ('SUBQ', 'SUBQ (Subcutaneous) - injecting into the fatty tissue'), ('NA', 'Not due for testosterone to be filled'), ('ENCLOMIPHENE', 'Enclomophine - Clomid')], default='N/A', max_length=255),
        ),
    ]
