# Generated by Django 4.1.5 on 2023-01-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_rename_orderitems_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationorder',
            name='enclomiphene',
            field=models.CharField(choices=[('0', '0'), ('30', '30 tabs $75'), ('60', '60 tabs $145')], default='0', max_length=255),
        ),
    ]
