# Generated by Django 4.1.5 on 2023-01-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_medicationorder_gonadorelin_nasal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationorder',
            name='sermorelin',
            field=models.CharField(choices=[('0', '0'), ('1', '1 Month $211.65'), ('2', '2 Month $400'), ('3', '3 Month $598')], default='0', max_length=25),
        ),
    ]
