# Generated by Django 4.1.5 on 2023-01-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_alter_patientorder_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationorder',
            name='medical_requests',
            field=models.TextField(blank=True, null=True, verbose_name='Comments or Requests'),
        ),
    ]
