# Generated by Django 4.1.5 on 2023-01-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0019_alter_medicationorder_medical_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationorder',
            name='gonadorelin_nasal',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=25, verbose_name='Gonadorelin Nasal Spray'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
