# Generated by Django 4.1.5 on 2023-01-30 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0020_alter_medicationorder_gonadorelin_nasal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.provider'),
        ),
    ]
